spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB


  application:
    name: platform
    jwt:
      secretKey: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  datasource:
    url: jdbc:mysql://localhost:3306/platform?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: jd123
    driver-class-name: com.mysql.cj.jdbc.Driver

    show-sql: false
    properties:
      hibernate:
        format_sql: true
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
<<<<<<< HEAD
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
=======
server:
  port: 8082

>>>>>>> 1ec7390efbbfd4d2deb16776d6bc7e8a62e36454
logging:
  level:
    root: debug

server:
  port: 8080